// Preço/nome autoritativos para a preferência de pagamento — nunca confiar no
// que o cliente manda, senão dá pra pagar R$0,01 por qualquer item via devtools.
// Mantenha isto em sincronia manualmente com src/data/gifts.js (a lista não
// muda com frequência, então duplicar aqui é mais simples que montar um passo
// de build só para isso).
export const GIFTS_CATALOG: Record<string, { name: string; price: number }> = {
  'gift-01': { name: 'Kit Cobre Leito Casal Colcha 3 Peças Boutis Estampada Dupla Face', price: 91.9 },
  'gift-02': { name: 'Cobre Leito Colcha Camili Super King 3 pçs Matelado Dupla Face', price: 140.9 },
  'gift-03': { name: 'Cobertor Casal Queen Alaska Sherpa e Manta Flanel (Marinho)', price: 189.89 },
  'gift-04': { name: 'Kit Cobre Leito Colcha 3 Peças Dupla Face Isabel Areia Boutis King', price: 99.9 },
  'gift-05': { name: 'Cobertor Casal Dupla Face com Manta e Pele de Carneiro (Sherpa) 2,20m x 2,40m', price: 179.9 },
  'gift-06': { name: 'Kit Cobre Leito Colcha Cama Casal Queen 3 Peças Essencialle Algodão 160 Fios Estampado', price: 206.04 },
  'gift-07': { name: 'Cobertor com Manga Manta Sherpa Microfibra Quentinho Aveludado', price: 186.19 },
  'gift-08': { name: 'Cobertor Casal Jolitex/Dyuri Ternille Gualdaquivir 180x220cm', price: 129.9 },
  'gift-09': { name: 'Cobertor Casal Jolitex/Dyuri Ternille Gualdaquivir 180x220cm', price: 129.9 },
  'gift-10': { name: 'Relógio de Parede Grande 40cm Luxuoso', price: 69.9 },
  'gift-11': { name: 'Quadro Decorativo Leão de Judá Religioso Grande', price: 78.9 },
  'gift-12': { name: 'Sofá-Cama Casal 3 Lugares Premium A2 Suede Azul Turquesa', price: 1305.67 },
  'gift-13': { name: 'Sapateira Articulada Bancada Hall de Entrada Organizador Multiuso', price: 199.9 },
  'gift-14': { name: 'Rack com Painel para TV até 65 Polegadas Life Marrom', price: 711.76 },
  'gift-15': { name: 'Conjunto Sala de Jantar Mesa Tampo de Madeira 4 Cadeiras Talita', price: 599.99 },
  'gift-16': { name: 'Guarda-Roupa Solteiro Denver 2 Portas de Correr com Espelho', price: 819.99 },
  'gift-17': { name: 'Gabinete de Banheiro em MDF com Pia Cuba - Veneto', price: 189.0 },
  'gift-18': { name: 'Aparelho de Jantar e Chá 20 Peças Cerâmica Redondo Branco e Azul Claro', price: 175.9 },
  'gift-19': { name: 'Painel para TV 55 Polegadas Marrom Moon', price: 528.24 },
  'gift-20': { name: 'Jogo de Pratos Fundo Brancos 6 Peças - Pétala', price: 69.98 },
  'gift-21': { name: 'Jogo de Panelas Caçarolas 9 Peças Antiaderente 6 Camadas de Teflon', price: 286.89 },
  'gift-22': { name: 'Kit Lixeira 5 Litros Inox com Pedal + Escova Sanitária Inox', price: 119.9 },
  'gift-23': { name: 'Boleira com Pé e Tampa de Vidro Pétalas Jasmin 32cm', price: 78.9 },
  'gift-24': { name: 'Mop Giratório com Cesto em Inox Preto', price: 78.9 },
  'gift-25': { name: 'Amassador de Latinha 475ml Reforçado com Abridor de Garrafa', price: 49.94 },
  'gift-26': { name: 'Panela Frigideira de Indução e Fogão a Gás Antiaderente Cerâmica Linha Premium', price: 54.77 },
  'gift-27': { name: 'Panela de Pressão 4,2L Preta Fechamento Externo Ceramic Life Pressure', price: 189.9 },
  'gift-28': { name: 'Smart TV 50" DLED Roku 4K WiFi HDR', price: 2099.0 },
  'gift-29': { name: 'Jogo de Panelas Alumínio Puro Fundido Batido Grosso 5 Peças', price: 214.9 },
  'gift-30': { name: 'Chaleira Bule de Vidro com Infusor de Chá em Inox 750ml', price: 58.9 },
  'gift-31': { name: 'Câmera WiFi Full HD Branca com Cartão 64GB', price: 351.72 },
  'gift-32': { name: 'Lixeira Automática Inteligente com Sensor 12L Cozinha', price: 101.9 },
  'gift-33': { name: 'Fechadura Biométrica Eletrônica Digital WiFi Inteligente com App', price: 369.0 },
  'gift-34': { name: 'Lixeira com Sensor Inteligente Automática 16 Litros para Banheiro', price: 174.0 },
  'gift-35': { name: 'Alexa Echo Dot 5ª Geração Novo Processador Som Premium Preto', price: 550.8 },
  'gift-36': { name: 'Echo Dot 5ª Geração Alexa Preta', price: 499.99 },
  'gift-37': { name: 'Caixa de Som Bluetooth Potente LED RGB Portátil + Microfone', price: 259.99 },
  'gift-38': { name: 'Robô Aspirador e Passa Pano Smart 100 com Sensor Anti-Queda', price: 568.17 },
  'gift-39': { name: 'Omeleteira Elétrica Easy Omelet Preta', price: 159.0 },
  'gift-40': { name: 'Chaleira Elétrica Aço Inox Café Bule 1,8 Litros Profissional', price: 69.99 },
  'gift-41': { name: 'Liquidificador Turbo Glass Copo de Vidro 12 Velocidades 1400W', price: 251.58 },
  'gift-42': { name: 'Batedeira Planetária 4L 850W Preto/Inox 220V', price: 644.44 },
  'gift-43': { name: 'Purificador Eletrônico Compacto Efficient Painel Mecânico Bivolt Cinza', price: 589.9 },
  'gift-44': { name: 'Purificador de Água E-Due Prata Bivolt', price: 600.0 },
  'gift-45': { name: 'Panela de Pressão Elétrica Digital', price: 399.0 },
  'gift-46': { name: 'Air Fryer Preto 6,5L', price: 409.47 },
  'gift-47': { name: 'Liquidificador 1400 Full Preto 15 Velocidades + Pulsar 1400W', price: 184.21 },
  'gift-48': { name: 'Sanduicheira 127V Grill Brunch', price: 100.77 },
  'gift-49': { name: 'Air Fryer Family Efficient Dark Red 5L com Timer', price: 390.9 },
  'gift-50': { name: 'Aspirador de Pó Vertical Silent Speed Max 1350W 220V', price: 184.9 },
  'gift-51': { name: 'Cervejeira Vertical Preta 82L Frost Free', price: 1788.42 },
  'gift-52': { name: 'Cervejeira Home Bar Vertical Preta 100L Frost Free', price: 2221.11 },
  'gift-53': { name: 'Cervejeira Vertical Beer Plus 264 Litros Inox', price: 3898.89 },
  'gift-54': { name: 'Freezer Vertical 196L Inverter', price: 2499.99 },
  'gift-55': { name: 'Lava-Louças de Embutir 15 Serviços Inox', price: 3698.69 },
  'gift-56': { name: 'Depurador e Exaustor de Ar Slim 60cm 3 Velocidades Titanium', price: 423.52 },
  'gift-57': { name: 'Depurador e Exaustor de Ar Slim 60cm 3 Velocidades Inox', price: 498.78 },
  'gift-58': { name: 'Cooktop 5 Bocas a Gás Supreme com Queimador Tripla Chama Mesa de Vidro', price: 689.9 },
  'gift-59': { name: 'Panela de Pressão Elétrica 5L Pratic Cook', price: 449.99 },
  'gift-60': { name: 'Air Fryer Oven 12L 4 em 1 1800W', price: 799.9 },
};
